logic of get host metadata from vc
vmware/flowgate pull request #566
Opened 2020-10-30 08:43 UTC by VMware-HaoyuLi

Signed-off-by: haoyul <haoyul@vmware.com>

2020-11-11 09:13 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +            mappings = restClient.getServerMappingsByVC(vc.getId()).getBody();
move the mapping before connect VC.

2020-11-11 09:33 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +
avoid unnecessary update

2020-11-12 09:40 UTC, yixingjia requested changes

2020-11-12 09:40 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +   public boolean checkServerMappingIsVaild(SDDCSoftwareConfig vc,
refactor this method

2020-11-12 09:40 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +      if (!vc.checkIsActive()) {
double check if this needed.

2020-11-12 09:40 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +            VsphereClient vsphereClient = connectVsphere(vc);
tru(){}

2020-11-12 09:40 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +            if (hosts != null && !hosts.isEmpty()) {
if (host emtpy){
log
return
}

2020-11-12 09:40 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +                        feedHostMetaData(hostMappingAsset, host, hostInfo);
boolean updateHostMetaData

2020-11-12 09:40 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +                        feedClusterMetaData(vsphereClient, hostMappingAsset, host, esxiMetadata,
Move call fetch cluster logic out of for.

2020-11-13 09:17 UTC, VMware-HaoyuLi commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +               ConfigInfoEx ci = (ConfigInfoEx) cluster.getConfigurationEx();
check api

2020-11-13 09:22 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +      if (!vc.checkIsActive()) {
Move to aggregator.

2020-11-13 09:22 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
>        if (!vcInfo.checkIsActive()) {
remove this when aggregator part finished.

2020-11-17 09:35 UTC, yixingjia requested changes

2020-11-17 09:35 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +                  logger.error("AssetId is null");
Let's add more information about the log.

2020-11-17 09:35 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +      RuntimeInfo runtimeInfo = host.getRuntime();
please check if it is call api or not.

2020-11-17 09:35 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +            needUpdate = needUpdate || (!fullName.equals(oldHostInfo.getHypervisorFullName()));
if(!fullName.equalse(xxxx){
  hostset(xxx)
 needupdate =true;
}

2020-11-17 09:35 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +               hostNic.setMacAddress(physicalNics[i].getMac());
Mac address is unique. 

1. compare map size

2. new {
  mac address ,check old map {
   
}else{
  oldmap put (new one)
}
}

2020-11-19 09:54 UTC, yixingjia requested changes

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +                  logger.error("host:" + mobId + " get asset is null");
Please add servermapping id in the log.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +                  logger.error("host:" + mobId + " get asset is null");
also logging the asset ID.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +   public boolean feedClusterMetaData(HashMap<String, ClusterComputeResource> clusterMap,
remove newhostFlag

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +      ConfigInfoEx ci = (ConfigInfoEx) cluster.getConfigurationEx();
configInfoExtension

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +      String clusterName = hostParent.getValue();
Why clustername here?  double check hostParent if it is a folder.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +      String clusterName = hostParent.getValue();
check when cannot find a cluster case.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +      DpmHostConfigInfo[] dhcis = ci.getDpmHostConfig();
let's try to avoid short name variable.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +      String clusterInstance =
it's not the right way to get vc instance uuid.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +   public boolean feedHostMetaData(HostSystem host, HostInfo hostInfo, boolean newHostFlag) {
remove newHostFlag

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +         if (newHostFlag || !maxRunningVMs.equals(hostInfo.getMaxRunningVms())) {
use value compare instead of object compare.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +         if (newHostFlag || !runtimeInfo.getConnectionState().toString()
use a variable for the connectionState.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +            for (int i = 0; i < nicsNum; i++) {
for( PhiscalNic phyiscalNic: physicalNics)

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +               hostNic.setDuplex(physicalNics[i].getLinkSpeed() == null ? false
let's check physicalNics.getLinkSpeed(){
set1()
set2()
}

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +            } else {
we need to remove the newHostFlag, then please refactor the follow code.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +                     HostNic oldValue = entry.getValue();
let's check object compare.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +            hostInfo.setDiskCapacity(diskCapacity);
TODO:  only count writeable datastore.

2020-11-19 09:54 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +            hostInfo.setDiskCapacity(diskCapacity);
add comment. say we will count shared datastore for each host, which will cause problem in calculate the total available storage among multiple hosts.

2020-11-23 09:37 UTC, yixingjia requested changes

2020-11-23 09:37 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +               if (hostJustification != null && !hostJustification.isEmpty()) {
host= new HostInfo()

2020-11-23 09:37 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +                        return;
return or continue?

2020-11-23 09:37 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +                  logger.info("No update required");
info->debug   better add the host identifier.

2020-11-23 09:37 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +                  return;
should continue?

2020-11-23 09:37 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +      if (hostParent == null || !hostParent.getType().equals("ClusterComputeResource")) {
use constant.

2020-11-23 09:37 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +      if (oldEsxiMetadataClusterDRSBehavior == null || !configInfoExtension.getDrsConfig().getDefaultVmBehavior().toString()
double check when drs is off , then what will happen to getDefaultVmBehavior() method.

2020-11-23 09:37 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +            String hostInfoHostModel = hostInfo.getHostModel();
double check if empty will turn into null

2020-11-23 09:37 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +               if (newHostNicMap.size() != oldHostNicMap.size() || !newHostNicMap.equals(oldHostNicMap)) {
should check the mac address , if any change of the mac address then it will need update the nic list.

2020-11-23 09:37 UTC, yixingjia commented on vc-worker/src/main/java/com/vmware/flowgate/vcworker/scheduler/job/VCDataService.java
> +         if (diskCapacity != hostInfo.getDiskCapacity()) {
should check writable datastore first.

2020-11-24 09:23 UTC, yixingjia approved these changes

2020-11-26 09:35 UTC, merged